// <auto-generated />
using System;
using MagicVilla_VillaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla_VillaAPI.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20230901180746_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_VillaAPI.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aminity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupation")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("SqFt")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aminity = "",
                            DateCreated = new DateTime(2023, 9, 1, 23, 37, 46, 638, DateTimeKind.Local).AddTicks(7193),
                            DateUpdated = new DateTime(2023, 9, 1, 23, 37, 46, 638, DateTimeKind.Local).AddTicks(7211),
                            Details = "This is a test roayal villa",
                            ImageUrl = "http://surl.li/kokus",
                            Name = "Royal Villa",
                            Occupation = 5,
                            Rate = 200.0,
                            SqFt = 550
                        },
                        new
                        {
                            Id = 2,
                            Aminity = "",
                            DateCreated = new DateTime(2023, 9, 1, 23, 37, 46, 638, DateTimeKind.Local).AddTicks(7213),
                            DateUpdated = new DateTime(2023, 9, 1, 23, 37, 46, 638, DateTimeKind.Local).AddTicks(7214),
                            Details = "This is a test roayal villa natural",
                            ImageUrl = "http://surl.li/kokvu",
                            Name = "Royal Villa 1",
                            Occupation = 3,
                            Rate = 500.0,
                            SqFt = 750
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
